version: '3.9'
services:
  nginx:
    build: ./docker/nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - laravel
    working_dir: /var/www/html
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl/server.crt:/etc/nginx/ssl/server.crt
      - ./docker/nginx/ssl/server.key:/etc/nginx/ssl/server.key
      - .:/var/www/html:cached
    restart: on-failure

  laravel:
    build: ./docker/laravel
    working_dir: /var/www/html
    volumes:
      - ./docker/laravel/src/php.ini:/usr/local/etc/php/php.ini
      - .:/var/www/html:cached

  redis:
    image: 'redis:latest'
    restart: on-failure

  memcached:
    image: 'memcached:latest'
    restart: on-failure

  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: lucas-sandery
      ADMINER_DEFAULT_SERVER: host.docker.internal:4306
    restart: on-failure

  db:
    image: mysql:8
    ports:
      - '4306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: app_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    tmpfs:
      - /var/lib/mysql
    restart: on-failure
